name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint==3.3.1
        pip install black==24.10.0
        pip install isort==5.13.2
    - name: Analysing the code with pylint
      run: |
        isort --check-only --profile=google $(git ls-files '*.py')
        black --check --line-length=120 $(git ls-files '*.py')
        pylint --rcfile .pylintrc $(git ls-files '*.py')
